debug: true
fps: 60
fullscreen: false
height: 860
resizable: true
theme:
  background_colour: '#282C34'
  complementary_colour: '#AAE300'
  number_font:
    filename: assets/fonts/JetBrainsMono-Bold.ttf
    font_size: 32
  subtitle_font:
    filename: null
    font_size: 48
  text_colour: '#AAE300'
  title_font:
    filename: null
    font_size: 64
  triad_colour: '#E33900'
version_number:
- 0
- 0
- 0
version_string: vUNKNOWN
vsync: true
width: 1200
